export const SLIDER_PRODUCTS = "SLIDER_PRODUCTS";
export const IMGPREV_PRODUCTS = "IMGPREV_PRODUCTS";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const BLOG1 = "BLOG1";
export const BLOG2 = "BLOG2";
export const ADD_SLIDER_PRODUCTS = 'ADD_SLIDER_PRODUCTS';
export const ADD_IMGPREV_PRODUCTS = 'ADD_IMGPREV_PRODUCTS';
export const ADD_FILTER_PRODUCTS = 'ADD_FILTER_PRODUCTS';
export const INC_PRODUCT = 'INC_PRODUCT';
export const DEC_PRODUCT = 'DEC_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const REMOVE_ALL = 'REMOVE_ALL';


